server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /user-api/ {
        proxy_pass http://${USER_SERVICE_HOST}:${USER_SERVICE_PORT}/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /store-api/ {
        proxy_pass http://${STORE_SERVICE_HOST}:${STORE_SERVICE_PORT}/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /product-api/ {
        proxy_pass http://${PRODUCT_SERVICE_HOST}:${PRODUCT_SERVICE_PORT}/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /config-api/ {
        proxy_pass http://${CONFIG_SERVICE_HOST}:${CONFIG_SERVICE_PORT}/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /company-api/ {
        proxy_pass http://${COMPANY_SERVICE_HOST}:${COMPANY_SERVICE_PORT}/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /customer-api/ {
        proxy_pass http://${CUSTOMER_SERVICE_HOST}:${CUSTOMER_SERVICE_PORT}/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /order-api/ {
        proxy_pass http://${ORDER_SERVICE_HOST}:${ORDER_SERVICE_PORT}/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}