server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /user-api/ {
        proxy_pass http://${user_service_host}:${user_service_port}/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /store-api/ {
        proxy_pass http://${store_service_host}:${store_service_port}/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /product-api/ {
        proxy_pass http://${product_service_host}:${product_service_port}/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /config-api/ {
        proxy_pass http://${config_service_host}:${config_service_port}/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /company-api/ {
        proxy_pass http://${company_service_host}:${company_service_port}/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /customer-api/ {
        proxy_pass http://${customer_service_host}:${customer_service_port}/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /order-api/ {
        proxy_pass http://${order_service_host}:${order_service_port}/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}