apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
  namespace: frontend
data:
  USER_SERVICE_URL: "/user-api"
  STORE_SERVICE_URL: "/store-api"
  ORDER_SERVICE_URL: "/order-api"
  PRODUCT_SERVICE_URL: "/product-api"
  CUSTOMER_SERVICE_URL: "/customer-api"
  COMPANY_SERVICE_URL: "/company-api"
  ABS_CONFIG_SERVICE_URL: "/config-api"