name: godaampe CI
on: 
  push:
    branches: [main]
  
jobs:
  # Keep Docker image name centralized so build/push use identical tags.
  # This avoids pushing to docker.io/library/godaampe, which is not writable.
  # Example resolved value: <docker-username>/godaampe:latest
  
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: npm
      
      - name: Install dependencies
        run: npm ci --include=optional
      
      - name: Build the application
        run: npm run build

      - name: package the application (Github artifact)
        run: npm pack

  push-image:
    runs-on: ubuntu-latest
    needs: build-image
    env:
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/godaampe
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image to Docker Hub
        run: docker push $IMAGE_NAME:${{ github.sha }}

      - name: Update Kubernetes manifest with new image tag
        run: |
          git clone https://github.com/Rahul-Bristlecone/godaampe-infra.git
          cd godaampe-infra/frontend/templates/
          sed -i "s|image: .*$IMAGE_NAME:.*|image: $IMAGE_NAME:${{ github.sha }}|" deployment.yaml

      - name: Commit and push manifest update
        run: |
          git config user.name "rahul-bristlecone"
          git config user.email "rsshrma92@hotmail.com"
          git add deployment.yaml
          git commit -m "Update image to $IMAGE_NAME:${{ github.sha }}"
          git push

# this is for reusable workflow to update the image tag in the argocd-infra repo
      # - name: Update infra repo with new image tag
      #   run: |
          # git clone https://github.com/<org>/argocd-infra.git
          # cd argocd-infra/backend/
      #     sed -i "s|image: .*$IMAGE_NAME:.*|image: $IMAGE_NAME:${{ github.sha }}|" deployment.yaml
      #     git config user.name "rahul-bristlecone"
      #     git config user.email "rsshrma92@hotmail.com"
      #     git add deployment.yaml
      #     git commit -m "Update backend image to $IMAGE_NAME:${{ github.sha }}"
      #     git push
        